---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faster
  name: gh-archived
  labels:
    app: gh-archived
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-archived
  template:
    metadata:
      labels:
        app: gh-archived
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8090'
    spec:
      volumes:
        - name: cache
          emptyDir: {}
      containers:
        - name: gh-archived
          image: ghcr.io/go-faster/gh-archive-clickhouse:main
          resources:
            requests:
              cpu: 250m
              memory: 256M
            limits:
              cpu: "1"
              memory: 512M
          ports:
            - containerPort: 8090
              protocol: TCP
              name: metrics
            - containerPort: 8080
              protocol: TCP
              name: http
          env:
            - name: HOME
              value: /cache
            - name: HTTP_ADDR
              value: 0.0.0.0:8080
            - name: METRICS_ADDR
              value: 0.0.0.0:8090
            - name: CLICKHOUSE_ADDR
              value: chendpoint-db.clickhouse.svc.cluster.local:9000
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: gh-archived
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gh-archived
                  key: CLICKHOUSE_PASSWORD
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gh-archived
                  key: GITHUB_TOKEN
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "8090"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=go-faster.gh-archive-ch"
            - name: OTEL_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
          volumeMounts:
            - mountPath: /cache
              name: cache
---
apiVersion: v1
kind: Service
metadata:
  namespace: faster
  name: gh-archived
  labels:
    app: gh-archived
    prometheus: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app: gh-archived
