---
apiVersion: v1
kind: Service
metadata:
  namespace: faster
  name: gh-archived
  labels:
    app: gh-archived
    prometheus: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8090
      name: metrics
  selector:
    app: gh-archived
