version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/*"
          - "go.opentelemetry.io/contrib/*"
      golang:
        patterns:
          - "golang.org/x/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
